INCLUDE globals.ink
#portrait:blank #speaker:Barkeep #layout:cg #audio:beep_1
...
*[Hey, Lloyd]
    ...
    **[Slow tonight, isn't it? Heh...]
    ...
    It is, Mr. Torrence...
    ...
        ***[Can I get a drink]
            ->DrinkChoice

=== DrinkChoice ===
...
...
Your hands.
They're <color=\#FF0000>DRENCHED</color> in red...
...
What have...
~notification("The Barkeep is disgusted...")
...What have you done?
...
*[I want a drink]
...
I serve PEOPLE here, sir.
...Not whatever you've become.
With absolutely no respect...
Get out of my sight.
And never come back.
        **[You'll regret this]
        Heheh...
        ~loadScene("Limbo")
        ->END
