INCLUDE globals.ink
#portrait:blank #speaker:Barkeep #layout:cg #audio:beep_1
...
*[Hey, Lloyd]
    ...
    **[Slow tonight, isn't it? Heh...]
    ...
    Yes.
    It is, Mr. Torrence.
    
    What'll it be?
        ->DrinkChoice

=== DrinkChoice ===
*[Bourbon]
    ...
    ~notification("The Barkeep is indifferent...")
    (He pours you a glass)
    (You slowly sip it)
    #layout:left 
    So... 
    What brings you out here?
    ...Not often we get strangers 'round these parts...
    The look in your eyes.
    ...
    ...
    You've got blood on your hands.
    ...
    Heh.
    These days...
    ...Who doesn't?
    Hahah...
    
    No judgement here, monsueir.
    ...
    **[What do I owe you?]
    ...
    It's on the house.
    Now, with all due respect...
    Get out of my sight.
        **[...]
        Come again...
        ~loadScene("Limbo")
        ->END
